/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala
}

scala {
    // Use Scala 3.
    version = "3.5.1"
    zincVersion = "1.10.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}


dependencies {
    implementation("org.scala-lang:scala3-library_3:3.5.1")
}

tasks.withType<ScalaCompile>().configureEach {
    scalaCompileOptions.apply {
        isForce = true
        additionalParameters = listOf("-java-output-version:17", "-explain", "-verbose")
    }
}